require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/grocery_items", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GroceryItem. As you add validations to GroceryItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GroceryItem.create! valid_attributes
      get grocery_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      grocery_item = GroceryItem.create! valid_attributes
      get grocery_item_url(grocery_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_grocery_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      grocery_item = GroceryItem.create! valid_attributes
      get edit_grocery_item_url(grocery_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GroceryItem" do
        expect {
          post grocery_items_url, params: { grocery_item: valid_attributes }
        }.to change(GroceryItem, :count).by(1)
      end

      it "redirects to the created grocery_item" do
        post grocery_items_url, params: { grocery_item: valid_attributes }
        expect(response).to redirect_to(grocery_item_url(GroceryItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GroceryItem" do
        expect {
          post grocery_items_url, params: { grocery_item: invalid_attributes }
        }.to change(GroceryItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post grocery_items_url, params: { grocery_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grocery_item" do
        grocery_item = GroceryItem.create! valid_attributes
        patch grocery_item_url(grocery_item), params: { grocery_item: new_attributes }
        grocery_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the grocery_item" do
        grocery_item = GroceryItem.create! valid_attributes
        patch grocery_item_url(grocery_item), params: { grocery_item: new_attributes }
        grocery_item.reload
        expect(response).to redirect_to(grocery_item_url(grocery_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        grocery_item = GroceryItem.create! valid_attributes
        patch grocery_item_url(grocery_item), params: { grocery_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested grocery_item" do
      grocery_item = GroceryItem.create! valid_attributes
      expect {
        delete grocery_item_url(grocery_item)
      }.to change(GroceryItem, :count).by(-1)
    end

    it "redirects to the grocery_items list" do
      grocery_item = GroceryItem.create! valid_attributes
      delete grocery_item_url(grocery_item)
      expect(response).to redirect_to(grocery_items_url)
    end
  end
end
